### ISSUE TITLE
Fix spot name text wrapping

### ISSUE THREAD

**Issue by eladkarakuli** [eladkarakuli/friend-surf#3]
On small screen sizes log spot name jumps to a new line, need to be wrapped/trimmed

![screenshot from 2015-11-25 18-02-41](https://cloud.githubusercontent.com/assets/1175894/11402104/cd351312-939e-11e5-8ac1-b687792afb76.png)

**Comment by danielkazak** [comment]
Resolved. We cannot trim nor wrap it. We must keep single line, therefore the font size was reduced slightly, no signifact change for user experience. (instead of developing responsive css just for this case.)
