### ISSUE TITLE
Customize reports page for small screens

### ISSUE THREAD

**Issue by eladkarakuli** [eladkarakuli/friend-surf#9]
Reports page should be responsive for smaller screens, elements rows should not jump to new lines:
![screen shot 2015-11-25 at 18 17 41](https://cloud.githubusercontent.com/assets/1175894/11402491/ebdb2304-93a0-11e5-9179-c98909aa9215.png)

**Comment by danielkazak** [comment]
Resolved, the col-xs\* values weren't summing complete 12 in a row.
